### ISSUE TITLE
testing frame.performance causes some versions of Chrome to crash

### ISSUE THREAD

**Issue by bluesmoon** [nicjansma/usertiming-compression.js#1]
As seen in the boomerang project, simply looking at `frame.performance` for some cross-origin frames can cause Chrome to crash.  We need to add the `frame.location` test before it to avoid this crash.

**Comment by nicjansma** [comment]
Fixed via https://github.com/nicjansma/usertiming-compression.js/commit/7ef308ab9d9f3eea84e0a3b5db8aecfbd251fb85
