### ISSUE TITLE
`from` check should be on `starTime + duration` for measures

### ISSUE THREAD

**Issue by bluesmoon** [nicjansma/usertiming-compression.js#2]
This code:

```
        if (options.from) {
            entries = entries.filter(function(e) {
                return e.startTime >= options.from;
            });
        }
```

Should be changed to this:

```
        if (options.from) {
            entries = entries.filter(function(e) {
                return e.startTime + e.duration >= options.from;
            });
        }
```

This is so because because entries that started before `from`, but ended after `from` were not available when `from` took place.

**Comment by nicjansma** [comment]
~~We want to capture things that either start or end within the timeframe, so a slightly different check:
`return (e.startTime >= options.from) || (e.startTime + e.duration >= options.from);`~~

EDIT: Nevermind, math

**Comment by nicjansma** [comment]
Fixed via https://github.com/nicjansma/usertiming-compression.js/commit/1cca4835da02053e2ff32b0f37d79990ac6ac603
