### ISSUE TITLE
Loading UserTimingDecompression via require is broken

### ISSUE THREAD

**Issue by tollmanz** [nicjansma/usertiming-compression.js#5]
The following code prints `undefined` to the console:

```js
const UserTimingDecompression = require('usertiming-compression').UserTimingDecompression;
console.log(UserTimingDecompression);
```

If I attempt to see where the module resolves, I get `/project-path/node_modules/usertiming-compression/src/usertiming-compression.js`:

```
console.log(require.resolve('usertiming-compression'));
```

In **package.json**, `main` is defined as `./src/usertiming-compression`, thus `./index.js` is being bypassed and the compression code is loaded.

I think that `main` should be removed from **package.json**, allowing the correct interface defined in **index.js** to be loaded. This ultimately allows for access to the decompression code via the documented method, `const UserTimingDecompression = require('usertiming-compression').UserTimingDecompression;`.

**Comment by nicjansma** [comment]
Absolutely correct!  Fixed via https://github.com/nicjansma/usertiming-compression.js/commit/bd6b81684509151f3bd3f8647aef47d5db098ff5

**Comment by tollmanz** [comment]
Thanks, @nicjansma! When you get a chance, can you push a new release to NPM?

**Comment by nicjansma** [comment]
@tollmanz d'oh forgot, pushed

**Comment by tollmanz** [comment]
Woot! Thanks so much @nicjansma! I can confirm that this works as intended now. Thanks for the quick work.
